package in.nimbo.dao;

import in.nimbo.TestUtility;
import in.nimbo.dao.pool.ConnectionWrapper;

import java.nio.file.Paths;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class DAOTest {
    private static ConnectionWrapper connection;
    private static ConnectionWrapper fakeConnection;

    private DAOTest() {}

    public static ConnectionWrapper getConnection() throws SQLException, ClassNotFoundException {
        if (connection != null)
            return connection;
        String initialH2Query = TestUtility.getFileContent(Paths.get("db/db_tables_sql.sql"));
        Class.forName(TestUtility.getDatabaseProperties().getProperty("database.driver"));
        connection = new ConnectionWrapper(DriverManager.getConnection(
                TestUtility.getDatabaseProperties().getProperty("database.url"),
                TestUtility.getDatabaseProperties().getProperty("database.username"),
                TestUtility.getDatabaseProperties().getProperty("database.password"))
        );

        connection.prepareStatement(initialH2Query).executeUpdate();
        return connection;
    }

    public static ConnectionWrapper getFakeConnection() {
        if (fakeConnection != null)
            return fakeConnection;

        fakeConnection = new ConnectionWrapper(null) {
            @Override
            public void close() {
                // do nothing
            }

            @Override
            public Statement createStatement() throws SQLException {
                throw new SQLException();
            }

            @Override
            public PreparedStatement prepareStatement(String sql) throws SQLException {
                throw new SQLException();
            }

            @Override
            public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
                throw new SQLException();
            }
        };
        return fakeConnection;
    }
}
