package in.nimbo.dao.pool;


import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class ConnectionWrapper implements AutoCloseable {
    private java.sql.Connection wrappedConnection;


    public ConnectionWrapper(java.sql.Connection wrappedConnection) {
        this.wrappedConnection = wrappedConnection;
    }

    @Override
    public void close() throws SQLException {
        wrappedConnection.close();
    }

    public Statement createStatement() throws SQLException {
        return wrappedConnection.createStatement();
    }

    public PreparedStatement prepareStatement(String sql)
            throws SQLException {
        return wrappedConnection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
            throws SQLException {
        return wrappedConnection.prepareStatement(sql, autoGeneratedKeys);
    }
}